version: '3'

services:
    mariadb:
        image: mariadb
        build: ./mariadb 
        restart: always
        expose:
            - "3306"
        volumes:
          - db_data:/var/lib/mysql
        networks:
          intra:
            ipv4_address: 172.25.0.10
        tty: true
        command: sh run_db.sh
    nginx:
        image: nginx
        build: ./nginx 
        restart: always
        ports:
            - "443:443"
        volumes:
          - wp_data:/var/www/html
        networks:
          intra:
            ipv4_address: 172.25.0.30
        tty: true
        command: sh run_ng.sh
    wordpress:
        image: wordpress
        build: ./wordpress 
        restart: always
        volumes:
            - wp_data:/var/www/html
        expose: 
            - "9000"
        networks:
          intra:
            ipv4_address: 172.25.0.20
        tty: true
        command: sh run_wp.sh
networks:
    intra:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: "172.25.0.0/24"
volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: /Users/parkjoungwan/DirForClone/data
      o: bind
  wp_data: 
    driver: local
    driver_opts:
      type: none
      device: /Users/parkjoungwan/DirForClone/data
      o: bind
