FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y && \
apt-get -y install php7.3 \
php-fpm \
php-cli \
wget \
curl \
php-mysql \
php-mbstring \
php-xml \
sendmail \
vim \
mariadb-client

COPY ./conf/run_wp.sh ./
COPY ./conf/wp-config.php ./tmp
COPY ./conf/www.conf ./tmp

